### ISSUE TITLE
Spek 0.8.5 won't compile on ubuntu 26.04 because of missing libavcodec/avfft.h in new version ffmpeg 8

### ISSUE THREAD

**Issue by jularnaud** [alexkay/spek#352]
Hello,

I have this error compiling spek 0.8.5 on the LTS version ubuntu 26.04 : 

spek-fft.cc:5:10: fatal error: libavcodec/avfft.h: No such file or directory
    5 | #include <libavcodec/avfft.h>

I think this [article](https://github.com/zmwangx/rust-ffmpeg-sys/issues/117) shows that ffmpeg 8 removed the libavcodec/avfft.h header.

Can you please update the code or makefile that we do not get the error anymore?

Best Regards,

**Comment by JPGuillemin** [comment]
confirmed here :)

up !!

**Comment by Skif-off** [comment]
[Fix compatibility with FFmpeg 8 - #338](https://github.com/alexkay/spek/pull/338)
?
